### ISSUE TITLE
lfs hangs on keybase shared folders

### ISSUE THREAD

**Issue by lemmy04** [Canop/dysk#44]
keybase provides (among other things) a shared fodler structure for users and teams that by default is kept in /keybase/. technically, it's a couple of fuse filesystems that get mounted as soon as the keybase client is running,

when you try to use lfs on any system that has keybase, lfs just quietly hangs and can't even be killed.

keybase is at https://keybase.io

**Comment by lemmy04** [comment]
I just updated to the latest keybase, and it seems to work ok now, i'll keep an eye on it for a few days tho.

**Comment by Canop** [comment]
Note that it's "normal" for lfs to hang for a few seconds when waiting for a disconnected or unreachable filesystem (it's worse when you use df). Maybe that was what you observed ?
