### ISSUE TITLE
lfs needs a man page

### ISSUE THREAD

**Issue by lemmy04** [Canop/dysk#45]
please create a manpage 

separated out from #39

**Comment by Canop** [comment]
The list of options is available with `lfs --help` but for this page to be useful you'd need to add at least the examples that can be found on https://dystroy.org/lfs/

**Comment by werdahias** [comment]
Ok, I'll look into it

**Comment by Canop** [comment]
Do you suggest lfs installs the man page, that a script be provided for that, or just to have the man page bundled with lfs ?

**Comment by heitorPB** [comment]
Can the man page be generated by Cargo at build time?

**Comment by werdahias** [comment]
iirc clap mangen can do that

**Comment by Canop** [comment]
@heitorPB lfs currently uses the argh library to manage its launch arguments. I don't think it supports man page generation. Regarding clap, that I use on other projects, I don't know how good it is to build interesting man pages with examples.

**Comment by werdahias** [comment]
@Canop I'd wite a manpage to be shipped with the debian package since that is required. You could use it however you see fit

**Comment by werdahias** [comment]
fyi: implementation with man:

https://github.com/dropbox/rust-brotli/pull/81/files
