### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./lfs)

### ISSUE THREAD

**Issue by xjzyy** [Canop/dysk#46]
解决办法：https://www.cnblogs.com/xjzyy/p/15932736.html

**Comment by Canop** [comment]
Please paste here the complete log. Don't link to an external site.

**Comment by Stargateur** [comment]
please try install lfs with cargo:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # https://rustup.rs/ install rust
cargo install lfs
```

Should work way better.

**Comment by DerPoet** [comment]
> 解决办法：https://www.cnblogs.com/xjzyy/p/15932736.html

Just use the "x86_64-unknown-linux-musl" variant. Works fine on older Linuxes, too. (For example, I use it on CentOS 7.)
