### ISSUE TITLE
Require rust/cargo 1.70 or newer?

### ISSUE THREAD

**Issue by johanneskastl** [Canop/dysk#69]
https://github.com/Canop/dysk/blob/b475e93b190281b041a5f33dccfc81378d87b415/Cargo.toml#L14

I get an error when building this with rust/cargo 1.59, as `anstream` does not like it:

```
[   46s] + /usr/bin/cargo auditable build -j4 --offline --release
[   47s] error: package `anstream v0.6.4` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
[   47s] Either upgrade to rustc 1.70.0 or newer, or use
[   47s] cargo update -p anstream@0.6.4 --precise ver
[   47s] where `ver` is the latest version of `anstream` supporting rustc 1.69.0

```

Would it make sense to increase the minimum rust version to 1.70?

**Comment by Canop** [comment]
I'm not a fan of forcing users to get the very last compiler version but I don't have a choice as clap always seems to require the last version (I checked, even the 4.3 asks for more recent than 1.59).

I'll change this, yes.
