### ISSUE TITLE
Show UUID`s

### ISSUE THREAD

**Issue by madeddy** [Canop/dysk#82]
Adding a option to have the disk/partitions UUIDs shown would imo of advantage.

Beside this, useful and good app. Thanks!

**Comment by Canop** [comment]
> disk/partitions UUIDs

Do you mean the filesystem's UUID or PARTUUID ? Or both ?

UUID is probably the most useful, and the one which makes most sense for dysk.

**Comment by madeddy** [comment]
A good question...
I think UUID is a must have and partuuid a maybe/useful bonus, as it can also always by other means obtained. So another way would be by showing the uuid as standard for the base view and `--show-partuuid` a cli option.

Greets

**Comment by Canop** [comment]
I'll probably define two columns and allow eg `dysk --cols +uuid+partuuid`.

**Comment by Canop** [comment]
Done
![image](https://github.com/user-attachments/assets/6f06a99f-860c-43d9-a69b-20687b527f63)

**Comment by madeddy** [comment]
Great! Thanks a lot.
